version: '3.3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
#    volumes:
#      - ~/apps/mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=michael
#      - MONGO_INITDB_ROOT_PASSWORD=michael
